spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://auth-service:8080}
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /auth/${segment}

            - id: user-service
              uri: ${USER_SERVICE_URL:http://user-service:8080}
              predicates:
                - Path=/api/users/**,/api/cards/**

            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://order-service:8080}
              predicates:
                - Path=/api/orders/**

            - id: payment-service
              uri: ${PAYMENT_SERVICE_URL:http://payment-service:8080}
              predicates:
                - Path=/api/payments/**
  web:
    error:
      include-message: always
      include-binding-errors: always
      include-exception: true

services:
  auth-service-url: ${AUTH_SERVICE_URL:http://auth-service:8080}
  user-service-url: ${USER_SERVICE_URL:http://user-service:8080}
  order-service-url: ${ORDER_SERVICE_URL:http://order-service:8080}

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true